CREATE TABLE expenses
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        date,
    category    VARCHAR(255),
    description VARCHAR(255),
    amount      DOUBLE PRECISION,
    CONSTRAINT pk_expenses PRIMARY KEY (id)
);